color:
  saturation: 0.4957447
  brandStrength: 0.1011465
  rhythmicContrast: 0.806383
  brandColors:
    - '#FFFFFF'
    - '#1C3633'
    - '#040509'
    - '#627F82'
    - '#C5C5C7'
  lightness: 0.6361702
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.9595745
typography_spectrum: 0.06170213
name: Graffitisea.com
