layout_spectrum: 0.9595745
typography_spectrum: 0.06170213
color:
  saturation: 0.4957447
  lightness: 0.6361702
  brandStrength: 0.1011465
  brandColors:
    - '#FFFFFF'
    - '#1C3633'
    - '#040509'
    - '#627F82'
    - '#C5C5C7'
  rhythmicContrast: 0.806383
name: Graffitisea.com
